conf/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from ikwen.core.views import DefaultHome

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', DefaultHome.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^coupon_detail/', include('ikwen.rewarding.urls', namespace='rewarding')),
    # url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    # url(r'^retail/', include('ikwen.partnership.urls', namespace='partnership')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    # url(r'^shavida/', include('ikwen_shavida.shavida.urls', namespace='shavida')),
    url(r'^webnode/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    # url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
)

echo/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import permission_required

from echo.collect import confirm_bundle_payment
from echo.views import SMSCampaignView, SMSHistory, SMSBundle, MailCampaignList, ChangeMailCampaign, MailBundle, \
    csv_uploader, PopupList, ChangePopup, PushCampaignList, ChangePushCampaign, PushBundle

urlpatterns = patterns(
    '',
    url(r'^pushCampaignList/$', permission_required('echo.ik_manage_messaging')(PushCampaignList.as_view()), name='pushcampaign_list'),
    url(r'^pushCampaign/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^pushCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^mailCampaignList/$', permission_required('echo.ik_manage_messaging')(MailCampaignList.as_view()), name='mailcampaign_list'),
    url(r'^mailCampaign/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^mailCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^sms/$', permission_required('echo.ik_manage_messaging')(SMSCampaignView.as_view()), name='sms_campaign'),
    url(r'^smsHistory/$', permission_required('echo.ik_manage_messaging')(SMSHistory.as_view()), name='sms_history'),
    url(r'^pops-up/$', permission_required('echo.ik_manage_popup')(PopupList.as_view()), name='popup_list'),
    url(r'^pop-up/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),
    url(r'^pop-up/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),

    url(r'^pushBundles/$', permission_required('echo.ik_manage_messaging')(PushBundle.as_view()), name='push_bundle'),
    url(r'^mailBundles/$', permission_required('echo.ik_manage_messaging')(MailBundle.as_view()), name='mail_bundle'),
    url(r'^smsBundles/$', permission_required('echo.ik_manage_messaging')(SMSBundle.as_view()), name='sms_bundle'),
    url(r'^confirm_bundle_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_bundle_payment, name='confirm_bundle_payment'),

    url(r'^csv_upload/$', csv_uploader, name='csv_uploader'),
)

templates/core/app_base_admin.html
{% extends "core/base_admin.html" %}
{% load i18n humanize static %}
{% block app_admin_nav %}
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="menus">
            <a href="javascript:;" data-toggle="collapse" data-target="#echo" style="padding-right: 0;">
                Echo
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="echo" class="nav nav-pills nav-stacked" style="padding-left: 15px;">
                <li class="push-campaigns">{% url 'echo:pushcampaign_list' as push_campaign_url %}
                    <a href="{{ push_campaign_url }}">
                        {% trans "Push" %}
                        <span class="label label-danger" style="text-transform: capitalize">New</span>
                    </a>
                </li>
                <li class="mail-campaigns">{% url 'echo:mailcampaign_list' as mail_campaign_url %}
                    <a href="{{ mail_campaign_url }}"> {% trans "Mail" %}</a>
                </li>
                <li class="sms-campaigns">{% url 'echo:sms_campaign' as sms_campaign_url %}
                    <a href="{{ sms_campaign_url }}">{% trans "SMS" %}</a>
                </li>
                {% comment %}<li class="echo-promotion">
                    <a href="{% url "echo:popup_list" %}">Pop-up</a>
                </li>{% endcomment %}
            </ul>
        </li>
        <hr>
        <li role="presentation" class="menus">
            <a href="javascript:;" data-toggle="collapse" data-target="#kako" style="padding-right: 0;">
                kako
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="kako" class="nav nav-pills nav-stacked" style="padding-left: 15px;">
                <li class="kako-categories">
                    <a href="{% url "revival:profiletag_list" %}">Profiles</a>
                </li>
            </ul>
        </li>
    </ul>
{% endblock %}