conf/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from ikwen.core.views import DefaultHome

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', DefaultHome.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^coupon_detail/', include('ikwen.rewarding.urls', namespace='rewarding')),
    # url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    # url(r'^retail/', include('ikwen.partnership.urls', namespace='partnership')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    # url(r'^shavida/', include('ikwen_shavida.shavida.urls', namespace='shavida')),
    url(r'^webnode/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    # url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
)

echo/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import permission_required

from echo.collect import confirm_bundle_payment
from echo.views import SMSCampaignView, SMSHistory, SMSBundle, MailCampaignList, ChangeMailCampaign, MailBundle, \
    csv_uploader, PopupList, ChangePopup, PushCampaignList, ChangePushCampaign, PushBundle

urlpatterns = patterns(
    '',
    url(r'^pushCampaignList/$', permission_required('echo.ik_manage_messaging')(PushCampaignList.as_view()), name='pushcampaign_list'),
    url(r'^pushCampaign/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^pushCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^mailCampaignList/$', permission_required('echo.ik_manage_messaging')(MailCampaignList.as_view()), name='mailcampaign_list'),
    url(r'^mailCampaign/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^mailCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^sms/$', permission_required('echo.ik_manage_messaging')(SMSCampaignView.as_view()), name='sms_campaign'),
    url(r'^smsHistory/$', permission_required('echo.ik_manage_messaging')(SMSHistory.as_view()), name='sms_history'),
    url(r'^pops-up/$', permission_required('echo.ik_manage_popup')(PopupList.as_view()), name='popup_list'),
    url(r'^pop-up/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),
    url(r'^pop-up/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),

    url(r'^pushBundles/$', permission_required('echo.ik_manage_messaging')(PushBundle.as_view()), name='push_bundle'),
    url(r'^mailBundles/$', permission_required('echo.ik_manage_messaging')(MailBundle.as_view()), name='mail_bundle'),
    url(r'^smsBundles/$', permission_required('echo.ik_manage_messaging')(SMSBundle.as_view()), name='sms_bundle'),
    url(r'^confirm_bundle_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_bundle_payment, name='confirm_bundle_payment'),

    url(r'^csv_upload/$', csv_uploader, name='csv_uploader'),
)

echo/views.py
# -*- coding: utf-8 -*-
import json
import logging
import os
import re
from threading import Thread

import requests
from ajaxuploader.views import AjaxFileUploader
from currencies.models import Currency
from django.conf import settings
from django.contrib import messages
from django.core import mail
from django.core.files import File
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.core.validators import EmailValidator
from django.db import transaction
from django.db.models import get_model
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template.defaultfilters import slugify

from django.views.generic import TemplateView
from django.utils.translation import gettext as _

from ikwen.conf import settings as ikwen_settings
from ikwen.conf.settings import WALLETS_DB_ALIAS

from ikwen.core.views import ChangeObjectBase, HybridListView
from ikwen.core.utils import send_sms, get_service_instance, DefaultUploadBackend, get_sms_label, add_event, \
    get_mail_content, get_model_admin_instance, get_item_list, send_push
from ikwen.accesscontrol.models import Member, PWAProfile
from ikwen.accesscontrol.backends import UMBRELLA
from ikwen.revival.models import ProfileTag, MemberProfile

from echo.admin import MailCampaignAdmin, PopUpAdmin, PushCampaignAdmin
from echo.models import SMSCampaign, MailCampaign, SMSObject, Balance, Bundle, SMS, MAIL, PopUp, PushCampaign, \
    PUSH
from echo.utils import count_pages, notify_for_low_messaging_credit

logger = logging.getLogger('ikwen')

ALL_SUBSCRIBER = "[All Subscriber]"
REGISTERED_SUBSCRIBER = "[Registered Subscriber]"
ANONYMOUS_SUBSCRIBER = "[Anonymous Subscriber]"
ALL_COMMUNITY = "[All Community]"
SELECTED_PROFILES = "[Selected profiles]"
FILE = "[File]"
INPUT = "[Input]"
PROFILES = "[Profiles]"


def batch_send_push(campaign):
    service = campaign.service
    campaign.keep_running = True
    if len(campaign.recipient_list) == 0:
        recipient_list = []
        subscriber_qs = PWAProfile.objects.filter(push_subscription__isnull=False)
        if campaign.recipient_src == ALL_SUBSCRIBER:
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    recipient_list.append(subscriber.id)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == REGISTERED_SUBSCRIBER:
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    try:
                        if subscriber.member:
                            recipient_list.append(subscriber.id)
                    except Member.DoesNotExist:
                        pass
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == ANONYMOUS_SUBSCRIBER:
            subscriber_qs = PWAProfile.objects.filter(push_subscription__isnull=False, member__isnull=True)
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    recipient_list.append(subscriber.id)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == PROFILES:
            checked_profile_tag_id_list = campaign.profile_tag_list
            member_qs = Member.objects.all()
            total = member_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_qs[start:finish]:
                    try:
                        profile = MemberProfile.objects.get(member=member)
                    except MemberProfile.DoesNotExist:
                        continue
                    match = set(profile.tag_fk_list) & set(checked_profile_tag_id_list)
                    if len(match) > 0:
                        try:
                            pwa_profile_qs = PWAProfile.objects.filter(push_subscription__isnull=False, member=member)
                            for pwa_profile in pwa_profile_qs:
                                recipient_list.append(pwa_profile.id)
                        except PWAProfile.DoesNotExist:
                            continue
                        if len(recipient_list) == 1:
                            campaign.save(using=UMBRELLA)
        campaign.recipient_list = recipient_list
        campaign.total = len(recipient_list)
        campaign.save(using=UMBRELLA)

    balance = Balance.objects.using('wallets').get(service_id=get_service_instance().id)
    push_count = campaign.total - campaign.progress
    if balance.push_count < push_count:
        try:
            notify_for_low_messaging_credit(service, balance)
        except:
            logger.error("Failed to notify %s for low messaging credit." % service, exc_info=True)
        return

    for pwa_profile_id in campaign.recipient_list[campaign.progress:]:
        pwa_profile = PWAProfile.objects.select_related('member').get(pk=pwa_profile_id)
        push_subscription = pwa_profile.push_subscription
        title = campaign.subject
        body = campaign.content
        target_page = campaign.cta_url
        try:
            if campaign.image:
                media_url = ikwen_settings.CLUSTER_MEDIA_URL + service.project_name_slug + '/'
                image_url = media_url + campaign.image.name
            else:
                image_url = ''
        except:
            image_url = ''
        if campaign.recipient_src != ANONYMOUS_SUBSCRIBER:
            try:
                if pwa_profile.member:
                    body = campaign.content.replace('$client', pwa_profile.member.first_name)
            except:
                body = campaign.content.replace('$client', "")
        if getattr(settings, 'ECHO_TEST', False):
            try:
                requests.get('http://www.google.com')
                balance.push_count -= 1
                balance.save()
            except requests.exceptions.RequestException:
                logger.error("Push to pwa_profile[%s] from %s not sent" % (pwa_profile_id, service), exc_info=True)
                break
        else:
            try:
                with transaction.atomic(using='wallets'):
                    if send_push(service, push_subscription, title, body, target_page, image_url):
                        balance.push_count -= 1
                        balance.save()
            except:
                logger.error("Atomic transaction from %s exit with error code" % service, exc_info=True)
                pass
        campaign = PushCampaign.objects.using(UMBRELLA).get(pk=campaign.id)
        campaign.progress += 1
        if not campaign.keep_running:
            campaign.save(using=UMBRELLA)
            break
        campaign.save(using=UMBRELLA)


def batch_send_mail(campaign):
    service = campaign.service
    config = service.config
    campaign.keep_running = True
    if len(campaign.recipient_list) == 0:
        recipient_list = []
        if campaign.recipient_src == ALL_COMMUNITY:
            member_queryset = Member.objects.all()
            total = member_queryset.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_queryset[start:finish]:
                    if EmailValidator(member.email):
                        recipient_list.append(member.email)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == PROFILES:
            checked_profile_tag_id_list = campaign.profile_tag_list
            member_queryset = Member.objects.all()
            total = member_queryset.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_queryset[start:finish]:
                    try:
                        profile = MemberProfile.objects.get(member=member)
                    except MemberProfile.DoesNotExist:
                        continue
                    match = set(profile.tag_fk_list) & set(checked_profile_tag_id_list)
                    if len(match) > 0:
                        if EmailValidator(member.email):
                            recipient_list.append(member.email)
                        if len(recipient_list) == 1:
                            campaign.save(using=UMBRELLA)
        campaign.recipient_list = recipient_list
        campaign.total = len(recipient_list)
        campaign.save(using=UMBRELLA)

    balance = Balance.objects.using('wallets').get(service_id=get_service_instance().id)
    mail_count = campaign.total - campaign.progress
    if balance.mail_count < mail_count:
        try:
            notify_for_low_messaging_credit(service, balance)
        except:
            logger.error("Failed to notify %s for low messaging credit." % service, exc_info=True)
        return
    connection = mail.get_connection()
    try:
        connection.open()
    except:
        logger.error("Failed to connect to mail server. Please check your internet" % service, exc_info=True)

echo/templates/echo/snippets/batch_progress.html
<script>
    ( () => {
        ikwen.updateProgressBar = () => {
            if ($('.event.running').length === 0) {
                clearInterval(ikwen.intervalId);
                return;
            }
            $('.event.running').each(function () {
                const campaignId = $(this).attr('id');
                const params = {action: 'get_campaign_progress', campaign_id: campaignId};

                $.getJSON('', params, function (data) {
                    let progressState = (data.progress / data.total) * 100;
                    $('#' + campaignId + ' .progress-bar').css('width', progressState + '%');
                    if (progressState === 100) $('#' + campaignId).removeClass('running')
                });
            });
        };
        ikwen.intervalId = setInterval(ikwen.updateProgressBar, 3000);
    })();
</script>

echo/templates/echo/snippets/campaign_modals.html
{% load i18n humanize static auth_tokens %}
<div id="modal-choose-recipient" class="modal fade modal-choose-recipient" tabindex="-1" role="dialog" aria-labelledby="modal-choose-recipient">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="text-align: center">
            <div class="modal-header no-border " style="background: #319dd5; color: #ffffff">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" style="color: #ffffff">&times;</span></button>
                <h4 class="modal-title" id="campaign_modal_title" style="text-align: center">{% trans "CONFIGURE YOUR AUDIENCE" %}</h4>
            </div>
            <div class="modal-body">
                <div class="">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-custom">
                            <div class="">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#importCSV">{% trans "Import contact from CSV file" %}</a>
                                </h4>
                            </div>
                            <div id="importCSV" class="panel-collapse collapse">
                                <div class="panel-body hidden-xs" style="padding-top: 1.5vh;">
{#                                    <a href="{% static "echo/ikwen_SMS_campaign_csv_model.csv" %}" style="text-decoration: none;">{% trans "Download CSV file model..." %}</a>#}
                                    <a href="{% get_static_prefix %}echo/{{ csv_model }}.csv" style="text-decoration: none;">{% trans "Download CSV file model..." %}</a>
                                </div>
                                <form>
                                  <div class="form-group">
                                      <div class="text-center" style="padding-top: 1vh;" id="csv-upload-container">
                                          <div class="uploader modal-campaign-uploader"></div>
                                          <div class="upload-csv-label"></div>
                                      </div>
                                  </div>
                                </form>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="panel panel-custom">
                            <div class="">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">{% trans "Send message to selected profile" %}</a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="" id="new-contact-profiles" style="padding-top: 2vh; text-align: left">
                                        <div class="row center-on-mobil">
                                        {% for profile in profiletag_list %}
                                            <div class="checkbox tile col-xs-6 col-sm-4 col-md-3">
                                                <label for="squaredThree">
                                                     <h5>
                                                         <input type="checkbox" id="{{ profile.id }}" value="{{ profile.id }}" name="profiles" class="profiles">
                                                         <label for="{{ profile.id }}" class="checkbox-label">{{ profile.name }}</label>
                                                     </h5>
                                                </label>
                                            </div>
                                        {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-custom">
                            <div class="">
                                <h4 class="panel-title">
                                    <a class="send-to-all" data-dismiss="modal" href="#">
                                        {% trans "Send campaign to all your community" %}&nbsp;&nbsp;<span class="badge badge-custom"> {{ member_count }} </span>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <p>CSS stands for Cascading Style Sheet. CSS allows you to specify various style properties for a given HTML element such as colors, backgrounds, fonts etc. <a href="https://www.tutorialrepublic.com/css-tutorial/" target="_blank">Learn more.</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer no-border" style="padding-top: 0 !important; text-align: center !important;">
                <button type="button" class="btn btn-success btn-confirm-modal " data-dismiss="modal">{% trans "Done" %}</button>
            </div>
        </div>
    </div>
</div>

<div id="insufficient-balance-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="insufficient-balance-modal" aria-hidden="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header no-border " style="background: #233682; color: #ffffff">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" style="color: #ffffff">&times;</span></button>
                <h4 class="modal-title" id="insufficient_balance_modal_title" style="text-align: center">{% trans "NOT ENOUGHT CREDIT..." %}</h4>
            </div>
            <div class="modal-body">
            <div class="detail-content text-center">
                <img alt="{% trans "Insufficient balance" %}">
            </div>
            </div>
            <div class="modal-footer no-border" style="text-align: center !important;">
                <button type="button" class="btn btn-primary"><a href="{% url 'echo:sms_bundle' %}" style="text-decoration: none; color: #ffffff">{% trans "Refill" %}</a></button>
            </div>
        </div>
    </div>
</div>

echo/templates/echo/snippets/embed_doc.html
{% load i18n static %}

    <div class="embed-doc tpl">
       <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed est eros,
            vulputate eget sodales nec, malesuada vel ante. Quisque volutpat risus in dolor sollicitudin
            a commodo libero suscipit. Nunc ultrices risus ut arcu hendrerit aliquet. Integer sit amet eros
            eu augue porttitor dictum. Quisque vel ante est, at lacinia tortor. Curabitur lacus purus, malesuada
            sit amet dapibus ac, placerat id leo.
       </div>
       <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title 2">
            Voici mon texte slide 2
       </div>
       <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title 3">
            Voici mon texte slide 3
       </div>
        <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title 4">
            Voici mon texte slide 4
       </div>
        <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title 5">
            Voici mon texte slide 5
       </div>
        <div class="embed-doc-page" data-img="{% static 'chat/img/change_me.png' %}" data-title="Put title 6">
            Voici mon texte slide 6
       </div>
    </div>

echo/templates/echo/snippets/push_campaign_modals.html
{% load i18n humanize static auth_tokens %}
<div id="modal-choose-recipient" class="modal fade modal-choose-recipient" tabindex="-1" role="dialog" aria-labelledby="modal-choose-recipient">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="text-align: center">
            <div class="modal-header no-border " style="background: #319dd5; color: #ffffff">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" style="color: #ffffff">&times;</span></button>
                <h4 class="modal-title" id="push_campaign_modal_title" style="text-align: center">{% trans "CONFIGURE YOUR AUDIENCE" %}</h4>
            </div>
            <div class="modal-body">
                <div class="">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-custom" style="display: none">
                            <div class="">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#importCSV">{% trans "Import contact from CSV file" %}</a>
                                </h4>
                            </div>
                            <div id="importCSV" class="panel-collapse collapse">
                                <div class="panel-body hidden-xs" style="padding-top: 1.5vh;">
                                    <a href="{% get_static_prefix %}echo/{{ csv_model }}.csv" style="text-decoration: none;">{% trans "Download CSV file model..." %}</a>
                                </div>
                                <form>
                                  <div class="form-group">
                                      <div class="text-center" style="padding-top: 1vh;" id="csv-upload-container">
                                          <div class="uploader modal-campaign-uploader"></div>
                                          <div class="upload-csv-label"></div>
                                      </div>
                                  </div>
                                </form>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    {% if subscriber_count > 0 or registered_subscriber_count > 0 %}
                        <div class="panel panel-custom">
                            <div>
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapsedCommunity">{% trans "Send campaign to my community" %}</a>
                                </h4>
                            </div>
                            <div id="collapsedCommunity" class="panel-collapse collapse">
                                <div class="panel-body text-center">
                                    {% if subscriber_count > 0 %}
                                   <div class="radio custom-radio">
                                       <h4><label><input type="radio" name="audience" class="option option-subscriber" value="[All Subscriber]">{% trans "All subscribers" %}&nbsp;&nbsp;<span class="badge badge-custom"> {{ subscriber_count }} </span></label></h4>
                                   </div>
                                    {% endif %}
                                    {% if anonymous_subscriber_count > 0 %}
                                    <div class="radio custom-radio">
                                        <h4><label><input type="radio" name="audience" class="option option-member" value="[Anonymous Subscriber]">{% trans "Anonymous subscribers" %}&nbsp;&nbsp;<span class="badge badge-custom"> {{ anonymous_subscriber_count }} </span></label></h4>
                                    </div>
                                    {% endif %}
                                    {% if registered_subscriber_count > 0 %}
                                    <div class="radio custom-radio">
                                        <h4><label><input type="radio" name="audience" class="option option-member" value="[Registered Subscriber]">{% trans "Members only" %}&nbsp;&nbsp;<span class="badge badge-custom"> {{ registered_subscriber_count }} </span></label></h4>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-custom">
                            <div>
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapsedProfile">{% trans "Send campaign to selected profile" %}</a>
                                </h4>
                            </div>
                            <div id="collapsedProfile" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="" id="new-contact-profiles" style="padding-top: 2vh; text-align: left">
                                        <div class="row center-on-mobil">
                                        {% for profile in profiletag_list %}
                                            <div class="checkbox tile col-xs-6 col-sm-4 col-md-3">
                                                <label for="squaredThree">
                                                     <h5>
                                                         <input type="checkbox" id="{{ profile.id }}" value="{{ profile.id }}" name="profiles" class="profiles">
                                                         <label for="{{ profile.id }}" class="checkbox-label">{{ profile.name }}</label>
                                                     </h5>
                                                </label>
                                            </div>
                                        {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% else %}
                            <div class="jumbotron" style="margin-bottom: 0">
                            <div class="text-center">
                                <h2>{% trans "You have not yet any subscriber" %}</h2>
                                <h4 class="text-muted">{% trans "Send Mail & SMS campaign to incite users to subscibe..." %}</h4>
                            </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="modal-footer no-border" style="padding-top: 0 !important; text-align: center !important;">
            {% if subscriber_count > 0 or registered_subscriber_count > 0 or anonymous_subscriber_count > 0 %}
                <button type="button" class="btn btn-success btn-confirm-modal misc-btn " data-dismiss="modal">{% trans "Done" %}</button>
            {% else %}
                <a href="{% url "echo:mailcampaign_list" %}" class="btn btn-success btn-modal">{% trans "Mail campaign" %}</a>
                <a href="{% url "echo:sms_campaign" %}" class="btn btn-success btn-modal">{% trans "SMS campaign" %}</a>
            {% endif %}
            </div>
        </div>
    </div>
</div>

<div id="insufficient-balance-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="insufficient-balance-modal" aria-hidden="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header no-border " style="background: #233682; color: #ffffff">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" style="color: #ffffff">&times;</span></button>
                <h4 class="modal-title" id="insufficient_balance_modal_title" style="text-align: center">{% trans "NOT ENOUGHT CREDIT..." %}</h4>
            </div>
            <div class="modal-body">
            <div class="detail-content text-center">
                <img alt="{% trans "Insufficient balance" %}">
            </div>
            </div>
            <div class="modal-footer no-border" style="text-align: center !important;">
                <button type="button" class="btn btn-primary"><a href="{% url 'echo:push_bundle' %}" style="text-decoration: none; color: #ffffff">{% trans "Refill" %}</a></button>
            </div>
        </div>
    </div>
</div>