conf/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from ikwen.core.views import DefaultHome

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', DefaultHome.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^coupon_detail/', include('ikwen.rewarding.urls', namespace='rewarding')),
    # url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    # url(r'^retail/', include('ikwen.partnership.urls', namespace='partnership')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    # url(r'^shavida/', include('ikwen_shavida.shavida.urls', namespace='shavida')),
    url(r'^webnode/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    # url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
)

echo/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import permission_required

from echo.collect import confirm_bundle_payment
from echo.views import SMSCampaignView, SMSHistory, SMSBundle, MailCampaignList, ChangeMailCampaign, MailBundle, \
    csv_uploader, PopupList, ChangePopup, PushCampaignList, ChangePushCampaign, PushBundle

urlpatterns = patterns(
    '',
    url(r'^pushCampaignList/$', permission_required('echo.ik_manage_messaging')(PushCampaignList.as_view()), name='pushcampaign_list'),
    url(r'^pushCampaign/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^pushCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangePushCampaign.as_view()), name='change_pushcampaign'),
    url(r'^mailCampaignList/$', permission_required('echo.ik_manage_messaging')(MailCampaignList.as_view()), name='mailcampaign_list'),
    url(r'^mailCampaign/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^mailCampaign/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_messaging')(ChangeMailCampaign.as_view()), name='change_mailcampaign'),
    url(r'^sms/$', permission_required('echo.ik_manage_messaging')(SMSCampaignView.as_view()), name='sms_campaign'),
    url(r'^smsHistory/$', permission_required('echo.ik_manage_messaging')(SMSHistory.as_view()), name='sms_history'),
    url(r'^pops-up/$', permission_required('echo.ik_manage_popup')(PopupList.as_view()), name='popup_list'),
    url(r'^pop-up/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),
    url(r'^pop-up/(?P<object_id>[-\w]+)/$', permission_required('echo.ik_manage_popup')(ChangePopup.as_view()), name='change_popup'),

    url(r'^pushBundles/$', permission_required('echo.ik_manage_messaging')(PushBundle.as_view()), name='push_bundle'),
    url(r'^mailBundles/$', permission_required('echo.ik_manage_messaging')(MailBundle.as_view()), name='mail_bundle'),
    url(r'^smsBundles/$', permission_required('echo.ik_manage_messaging')(SMSBundle.as_view()), name='sms_bundle'),
    url(r'^confirm_bundle_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_bundle_payment, name='confirm_bundle_payment'),

    url(r'^csv_upload/$', csv_uploader, name='csv_uploader'),
)

echo/views.py
# -*- coding: utf-8 -*-
import json
import logging
import os
import re
from threading import Thread

import requests
from ajaxuploader.views import AjaxFileUploader
from currencies.models import Currency
from django.conf import settings
from django.contrib import messages
from django.core import mail
from django.core.files import File
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.core.validators import EmailValidator
from django.db import transaction
from django.db.models import get_model
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template.defaultfilters import slugify

from django.views.generic import TemplateView
from django.utils.translation import gettext as _

from ikwen.conf import settings as ikwen_settings
from ikwen.conf.settings import WALLETS_DB_ALIAS

from ikwen.core.views import ChangeObjectBase, HybridListView
from ikwen.core.utils import send_sms, get_service_instance, DefaultUploadBackend, get_sms_label, add_event, \
    get_mail_content, get_model_admin_instance, get_item_list, send_push
from ikwen.accesscontrol.models import Member, PWAProfile
from ikwen.accesscontrol.backends import UMBRELLA
from ikwen.revival.models import ProfileTag, MemberProfile

from echo.admin import MailCampaignAdmin, PopUpAdmin, PushCampaignAdmin
from echo.models import SMSCampaign, MailCampaign, SMSObject, Balance, Bundle, SMS, MAIL, PopUp, PushCampaign, \
    PUSH
from echo.utils import count_pages, notify_for_low_messaging_credit

logger = logging.getLogger('ikwen')

ALL_SUBSCRIBER = "[All Subscriber]"
REGISTERED_SUBSCRIBER = "[Registered Subscriber]"
ANONYMOUS_SUBSCRIBER = "[Anonymous Subscriber]"
ALL_COMMUNITY = "[All Community]"
SELECTED_PROFILES = "[Selected profiles]"
FILE = "[File]"
INPUT = "[Input]"
PROFILES = "[Profiles]"


def batch_send_push(campaign):
    service = campaign.service
    campaign.keep_running = True
    if len(campaign.recipient_list) == 0:
        recipient_list = []
        subscriber_qs = PWAProfile.objects.filter(push_subscription__isnull=False)
        if campaign.recipient_src == ALL_SUBSCRIBER:
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    recipient_list.append(subscriber.id)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == REGISTERED_SUBSCRIBER:
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    try:
                        if subscriber.member:
                            recipient_list.append(subscriber.id)
                    except Member.DoesNotExist:
                        pass
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == ANONYMOUS_SUBSCRIBER:
            subscriber_qs = PWAProfile.objects.filter(push_subscription__isnull=False, member__isnull=True)
            total = subscriber_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for subscriber in subscriber_qs[start:finish]:
                    recipient_list.append(subscriber.id)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == PROFILES:
            checked_profile_tag_id_list = campaign.profile_tag_list
            member_qs = Member.objects.all()
            total = member_qs.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_qs[start:finish]:
                    try:
                        profile = MemberProfile.objects.get(member=member)
                    except MemberProfile.DoesNotExist:
                        continue
                    match = set(profile.tag_fk_list) & set(checked_profile_tag_id_list)
                    if len(match) > 0:
                        try:
                            pwa_profile_qs = PWAProfile.objects.filter(push_subscription__isnull=False, member=member)
                            for pwa_profile in pwa_profile_qs:
                                recipient_list.append(pwa_profile.id)
                        except PWAProfile.DoesNotExist:
                            continue
                        if len(recipient_list) == 1:
                            campaign.save(using=UMBRELLA)
        campaign.recipient_list = recipient_list
        campaign.total = len(recipient_list)
        campaign.save(using=UMBRELLA)

    balance = Balance.objects.using('wallets').get(service_id=get_service_instance().id)
    push_count = campaign.total - campaign.progress
    if balance.push_count < push_count:
        try:
            notify_for_low_messaging_credit(service, balance)
        except:
            logger.error("Failed to notify %s for low messaging credit." % service, exc_info=True)
        return

    for pwa_profile_id in campaign.recipient_list[campaign.progress:]:
        pwa_profile = PWAProfile.objects.select_related('member').get(pk=pwa_profile_id)
        push_subscription = pwa_profile.push_subscription
        title = campaign.subject
        body = campaign.content
        target_page = campaign.cta_url
        try:
            if campaign.image:
                media_url = ikwen_settings.CLUSTER_MEDIA_URL + service.project_name_slug + '/'
                image_url = media_url + campaign.image.name
            else:
                image_url = ''
        except:
            image_url = ''
        if campaign.recipient_src != ANONYMOUS_SUBSCRIBER:
            try:
                if pwa_profile.member:
                    body = campaign.content.replace('$client', pwa_profile.member.first_name)
            except:
                body = campaign.content.replace('$client', "")
        if getattr(settings, 'ECHO_TEST', False):
            try:
                requests.get('http://www.google.com')
                balance.push_count -= 1
                balance.save()
            except requests.exceptions.RequestException:
                logger.error("Push to pwa_profile[%s] from %s not sent" % (pwa_profile_id, service), exc_info=True)
                break
        else:
            try:
                with transaction.atomic(using='wallets'):
                    if send_push(service, push_subscription, title, body, target_page, image_url):
                        balance.push_count -= 1
                        balance.save()
            except:
                logger.error("Atomic transaction from %s exit with error code" % service, exc_info=True)
                pass
        campaign = PushCampaign.objects.using(UMBRELLA).get(pk=campaign.id)
        campaign.progress += 1
        if not campaign.keep_running:
            campaign.save(using=UMBRELLA)
            break
        campaign.save(using=UMBRELLA)


def batch_send_mail(campaign):
    service = campaign.service
    config = service.config
    campaign.keep_running = True
    if len(campaign.recipient_list) == 0:
        recipient_list = []
        if campaign.recipient_src == ALL_COMMUNITY:
            member_queryset = Member.objects.all()
            total = member_queryset.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_queryset[start:finish]:
                    if EmailValidator(member.email):
                        recipient_list.append(member.email)
                    if len(recipient_list) == 1:
                        campaign.save(using=UMBRELLA)
        elif campaign.recipient_src == PROFILES:
            checked_profile_tag_id_list = campaign.profile_tag_list
            member_queryset = Member.objects.all()
            total = member_queryset.count()
            chunks = total / 500 + 1
            for i in range(chunks):
                start = i * 500
                finish = (i + 1) * 500
                for member in member_queryset[start:finish]:
                    try:
                        profile = MemberProfile.objects.get(member=member)
                    except MemberProfile.DoesNotExist:
                        continue
                    match = set(profile.tag_fk_list) & set(checked_profile_tag_id_list)
                    if len(match) > 0:
                        if EmailValidator(member.email):
                            recipient_list.append(member.email)
                        if len(recipient_list) == 1:
                            campaign.save(using=UMBRELLA)
        campaign.recipient_list = recipient_list
        campaign.total = len(recipient_list)
        campaign.save(using=UMBRELLA)

    balance = Balance.objects.using('wallets').get(service_id=get_service_instance().id)
    mail_count = campaign.total - campaign.progress
    if balance.mail_count < mail_count:
        try:
            notify_for_low_messaging_credit(service, balance)
        except:
            logger.error("Failed to notify %s for low messaging credit." % service, exc_info=True)
        return
    connection = mail.get_connection()
    try:
        connection.open()
    except:
        logger.error("Failed to connect to mail server. Please check your internet" % service, exc_info=True)

echo/templates/echo/campaign_base.html
{% extends 'core/change_object_base.html' %}
{% load i18n humanize staticfiles auth_tokens %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'echo/css/swiper.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'ikwen/ajaxuploader/css/fileuploader.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'embed-doc/css/embed-doc.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'echo/css/echo.css' %}?V=20.06.07:05.35"/>
{% endblock %}

{% block head_js %}
    {{ block.super }}
    <script src="{% static 'ikwen/ajaxuploader/js/fileuploader.js' %}" ></script>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'echo/js/bootstrap-datepicker.js' %}" ></script>
    <script src="{% static 'echo/js/swiper.min.js' %}" ></script>
    <script src="{% static 'embed-doc/js/embed-doc.js' %}" ></script>
    <script>
        ( () => {
            $('#admin-content .modal').each(function() {
                $(this).appendTo('body')
            });
            let csv_name = '';
            ikwen.checkedProfiles = [];
            const uploader = new qq.FileUploader({
                template:
                '<div class="qq-uploader">' +
                    '<div class="qq-upload-drop-area"><span></span></div>' +
                    '<div class="qq-upload-button">' +
                        '<img class="modal-icon pb-10" src="{% static 'echo/img/import-csv-small.png' %}"' +
                            'style="cursor: pointer;"' +
                            'title="{% trans 'Import contact list from CSV file to send campaign' %}">' +
                    '</div>' +
                    '<ul class="qq-upload-list"></ul>' +
                '</div>',
                allowedExtensions: ['csv'],
                action: "{% url 'echo:csv_uploader' %}",
                element: $('div#csv-upload-container .uploader')[0],
                buttonText: "{% trans "Upload cover" %}",
                multiple: false,
                onProgress: (id, fileName, loaded, total) => {
                    $('body').css('cursor', 'wait')
                },
                onComplete: (id, fileName, responseJSON) => {
                    $('body').css('cursor', 'default');
                    if(responseJSON.success) {
                        ikwen.filename = responseJSON.filename;
                        csv_name = ikwen.filename.split('.').shift();
                        $('.upload-csv-label').text(csv_name);
                        $('.recipient-list').addClass('text-center').removeClass('warning').attr("readonly", "readonly").val(csv_name);
                        $('.reset-recipient-list').show();
                        $('.filename').val(ikwen.filename);
                        $('.btn-continue').removeClass('not-allowed');
                        $('.profile-checked').removeAttr('value');
                    } else {
                        alert("{% trans 'upload failed!' %}");
                    }
                },
                message: {
                    typeError: "Please give a valid CSV file, use our given example to avoid error."
                },
                params: {
                    'csrf_token': '{{ csrf_token }}',
                    'csrf_name': 'csrfmiddlewaretoken',
                    'csrf_xname': 'X-CSRFToken'
                }
            });

            $('.btn-confirm-modal').click( () => {
                let audience = [];
                $("input[name='profiles']:checked").each(function () {
                    ikwen.checkedProfiles.push($(this).val());
                });
                if (ikwen.checkedProfiles.length !== 0) {
                    $('.profile-checked').val(ikwen.checkedProfiles.join(','));
                    $('.recipient-list').addClass('text-center').removeClass('warning').attr("readonly", "readonly").val('[Selected profiles]');
                    $('.btn-continue').removeClass('not-allowed');
                    $('.filename').removeAttr('value');
                    $('.reset-recipient-list').show()
                }
                $("input[name='audience']:checked").each(function () {
                    audience.push($(this).val())
                });
                if (audience.length !== 0) {
                    $('.audience-choose').val(audience);
                    $('.recipient-list').addClass('text-center').removeClass('warning').attr("readonly", "readonly").val(audience);
                    $('.btn-continue').removeClass('not-allowed');
                    $('.filename').removeAttr('value');
                }
            });

            $('.misc-btn').click( () => {
                $('.reset-recipient-list').hide()
            });


            if ($('#subject').val() !== '') $('#subject').removeClass('warning');
            if ($('.sms-text').val() !== '') $('.sms-text').removeClass('warning');

            $('.send-to-all').click( () => {
                csv_name = '';
                $('.upload-csv-label').text(csv_name);
                $('.recipient-list').addClass('text-center').removeClass('warning').attr("readonly", "readonly").val('[All Community]');
                $('.filename').removeAttr('value');
                $('.profile-checked').removeAttr('value');
                $('.btn-continue').removeClass('not-allowed');
                $('.reset-recipient-list').show()
            });

            $('.reset-recipient-list').click(function () {
                csv_name = '';
                $('.upload-csv-label').text(csv_name);
                $('input:checkbox.profiles').removeAttr('checked');
                $('.collapse').removeClass('in');
                $('.recipient-list').removeClass('text-center').removeAttr("readonly").focus().val("");
                $('.btn-continue').addClass('not-allowed');
                $('.filename').removeAttr('value');
                $('.profile-checked').removeAttr('value');
                $(this).hide();
            });

            $('.recipient-list').keyup(function () {
                if ($(this).val() !== '') {
                    $(this).removeClass('warning');
                    $('.btn-continue').removeClass('not-allowed');
                }
                else {
                    $(this).addClass('warning');
                    $('.btn-continue').addClass('not-allowed')
                }

                $('.filename').removeAttr('value');
                $('.profile-checked').removeAttr('value');
            });

            $('#subject').keyup(function () {
                if ($(this).val() !== '') $(this).removeClass('warning');
            });
        })();

        embedDoc.initEmbedDoc("{% trans "Remind me later" %}", "{% trans "Got it!" %}", "{% trans "Show Help" %}");
    </script>
    {% include 'echo/snippets/batch_progress.html' %}
{% endblock %}

echo/templates/echo/mail_bundle.html
{% extends 'core/app_base_admin.html' %}
{% load i18n humanize static auth_tokens %}

{% block page_title %}
    <title> {% trans "Email Bundles" %} - ikwen</title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'echo/css/echo.css' %}?v=05.20.20" />
    <link rel="stylesheet" type="text/css" href="{% static 'echo/css/bootstrap-slider.min.css' %}">
    <style>
        .custom-bundle-cost {font-weight: bold !important;}
        .slider.slider-horizontal { margin: auto; width: 100% !important;}
        .slider-selection { background-image: -webkit-linear-gradient(left,#e1f1ff 0,#9dd1ff 100%); background-image: -o-linear-gradient(left,#e1f1ff 0,#9dd1ff 100%); background-image: linear-gradient(to left,#e1f1ff 0,#9dd1ff 100%); }
        .slider-handle { background-color: #016FF9!important; background-image: -webkit-linear-gradient(top,#348EFE 0,#016FF9 100%); background-image: -o-linear-gradient(top,#348EFE 0,#016FF9 100%); background-image: linear-gradient(to bottom,#348EFE 0,#016FF9 100%);
                        border-radius: 3px; }
        .tooltip-inner { background-color: #016FF9!important; }
        .tooltip-arrow { border-bottom-color: #016FF9!important; border-top-color: #016FF9!important; }
    </style>
{% endblock %}

{% block breadcrumb_location %}
    <li>{% trans "Email pricing plan" %}</li>
{% endblock %}

{% block admin_content %}
    <div id="admin-content">
        <div class="container-fluid">
            <div class="sold" style="text-align: right">
                <strong>{% trans "Remainig Email : " %}<span class="balance">{{ balance.mail_count|intcomma }}</span></strong>
            </div>
            <section class="bundle">
                <div id="stage" style="float: none; margin: auto">
                    <div class="predefined-bundle">
                        <h3 class="text-center">{% trans "Choose one pack below"%}</h3>
                        <hr>
                        <div class="panel bundle-pricing-table" data-bundle-type="{{ bundle_list.0.type }}">>
                            {% for bundle in bundle_list %}
                                <div class="col-sm-4">
                                    <div class="bundle-pricing-plan bundle-{{ bundle.name | lower }}" data-unit-cost="{{ bundle.unit_cost }}" data-value="{{ bundle.credit }}">
                                        <img class="img-responsive pricing-img" src="{{ settings.IKWEN_MEDIA_URL }}{{ bundle.image.name }}" alt="">
                                        <h3 class="bundle-header">{{ bundle.name }}</h3>
                                        <div class="bundle-features">
                                            <span class="bundle-features-item">{{ bundle.credit|intcomma }} Mails</span>
                                        </div>
                                        <p class="bundle-price"> <span class="currency">XAF</span> {{ bundle.cost | intcomma }}</p>
                                        <button class=" btn btn-primary btn-buy-bundle payment-start" data-product-id="{{ bundle.id }}">{% trans "Buy" %}</button>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="custom-bundle">
                        <h3 class="text-center" style="margin-top: 10vh">{% trans "Or customize your bundle"%}</h3>
                        <hr class="separator">
                        <div class="panel" style="margin-top: 5vh ">
                            <div class="addon-item" style="padding-bottom: 3vh">
                                <div class="col-lg-6" style="border-right: #3c3c3c 2px solid; text-align: left">
                                    <h4><label  style="cursor: pointer"><input id="CustomBundleEnabled" type="checkbox"/> &nbsp;{% trans " Want customize my bundle" %}</label></h4>
                                </div>
                                <div class="col-lg-6" style="text-align: right">
                                    <h4><label id="CurrentSliderPriceValLabel">{% trans "How much Mails do you want?" %}</label>&nbsp;<label id="CurrentSliderPriceVal" class="price tpl"></label></h4>
                                </div>
                            </div>
                            <div style="padding-bottom: 5.5vh; z-index: 10">
                                <input id="optionalMailsNumber" type="range" data-slider-min="1000" data-slider-max="150000" data-slider-step="500" data-slider-value="100" data-slider-enabled="false"/>
                            </div>
                            <div class="text-center">
                                <button class=" btn btn-primary btn-buy-bundle custom-bundle-validation payment-start" disabled>{% trans "Buy" %}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    {% with payment_conf='messaging_bundle' %}
        {% include 'billing/snippets/modal_payment_options.html' %}
    {% endwith %}
{% endblock %}

{% block js %}
    {{ block.super }}
{#    <script src="{% static 'echo/js/jquery-1.12.4.min.js' %}"></script>#}
    <script src="{% static 'echo/js/bootstrap-slider.min.js' %}"></script>
    <script>
        (() => {
            $('<input type="hidden" name="custom_bundle_value">').appendTo('#payment-start-flow');
            $('<input type="hidden" name="bundle_type">').appendTo('#payment-start-flow');
            $("#CustomBundleEnabled").prop("checked", false);

            const diamondValue = parseInt($('.bundle-diamond').data('value'));
            const goldValue = parseInt($('.bundle-gold').data('value'));

            const diamondPrice = parseFloat($('.bundle-diamond').data('unit-cost'));
            const goldPrice = parseFloat($('.bundle-gold').data('unit-cost'));
            const silverPrice = parseFloat($('.bundle-silver').data('unit-cost'));

            let customBundleCost = $("#optionalMailsNumber").data('slider-min');
            let bundleCost = silverPrice;
            let bundleValue = $("#optionalMailsNumber").data('slider-min');

            let optionalMailNumberSlider = new Slider("input#optionalMailsNumber",{
                tooltip: 'always',
                handle: 'square',
                tooltip_position: 'bottom',
            });
            $(".tooltip-main.in").css('display', 'none');


            $("#CustomBundleEnabled").click(function() {
                if(this.checked) {
                    $(".predefined-bundle .btn-buy-bundle").prop("disabled", true);
                    $(".custom-bundle .btn-buy-bundle").prop("disabled", false);
                    optionalMailNumberSlider.enable();
                    $(".tooltip-main.in").css('display', 'block');
                    bundleValue= parseInt(optionalMailNumberSlider.getValue());
                    customBundleCost= bundleValue * bundleCost;
                    $("#CurrentSliderPriceValLabel").text(" " + bundleValue.formatMoney(0, '{{ settings.THOUSAND_SEPARATOR }}', '{{ settings.DECIMAL_SEPARATOR }}') + " Mails = ");
                    $("#CurrentSliderPriceVal").removeClass('tpl').text(customBundleCost.formatMoney(0, '{{ settings.THOUSAND_SEPARATOR }}', '{{ settings.DECIMAL_SEPARATOR }}') + " XAF");
                    $('input[name=product_id]').val('');
                    $('input[name=bundle_type]').val('Mail');
                    $('input[name=custom_bundle_value]').val(bundleValue);
                }
                else {
                    $(".predefined-bundle .btn-buy-bundle").prop("disabled", false);
                    $(".custom-bundle .btn-buy-bundle").prop("disabled", true);
                    optionalMailNumberSlider.refresh();
                    bundleCost= silverPrice;
                    customBundleCost = silverPrice;
                    $("#CurrentSliderPriceValLabel").text("How much Mails do you want?");
                    $('#CurrentSliderPriceVal').addClass('tpl');
                    optionalMailNumberSlider.disable();
                    $(".tooltip-main.in").css('display', 'none');
                    $('input[name=bundle_type]').val('');
                    $('input[name=custom_bundle_value]').val('')
                }

            });
            $("#optionalMailsNumber").on("change", function(slideEvt) {
                bundleValue = parseInt(slideEvt.value.newValue);
                if (bundleValue >= diamondValue) bundleCost = diamondPrice;
                else if (bundleValue >= goldValue) bundleCost = goldPrice;
                else bundleCost = silverPrice;


                customBundleCost = bundleValue * bundleCost;
                $("#CurrentSliderPriceValLabel").text(" " + bundleValue.formatMoney(0, '{{ settings.THOUSAND_SEPARATOR }}', '{{ settings.DECIMAL_SEPARATOR }}') + " Mails = ");
                $("#CurrentSliderPriceVal").text(customBundleCost.formatMoney(0, '{{ settings.THOUSAND_SEPARATOR }}', '{{ settings.DECIMAL_SEPARATOR }}') + " XAF");
                $('input[name=product_id]').val('');
                $('input[name=custom_bundle_value]').val(bundleValue);
                $('input[name=bundle_type]').val($('.bundle-pricing-table').data('bundle-type'));
            });
        })()



    </script>
{% endblock %}